### ISSUE TITLE
Avenir not loading on srcdoc custom extension

### ISSUE THREAD

**Issue by weotch** [contentful/forma-36#211]
I recently made https://github.com/BKWLD/contentful-color-selector and it's small enough to be installed via `srcdoc`.   I read on https://github.com/contentful/forma-36

> Forma 36 was designed to use ‘Avenir Next’ as primary font family. If a package is used in the context of app.contentful.com (e.g UI extensions) this font will be provided.

However, I'm not seeing it.  I added the `f36-font-family--sans-serif` class to the body of my component in an attempt to set the `font-family` correctly: https://github.com/BKWLD/contentful-color-selector/blob/master/src/index.html#L7.  I'm loading that CSS here: https://github.com/BKWLD/contentful-color-selector/blob/master/src/index.js#L11.

I have an example of this UI Extension in use here: https://app.contentful.com/spaces/vrkkgjbn4fsk/entries/1VfqdjOBbin8EO6hwalKrU.  Here's what it looks like in Chrome:

![](http://yo.bkwld.com/a9934f465212/Image%202019-05-31%20at%208.51.58%20PM.png)

Here is Chrome's computed styles:

![](http://yo.bkwld.com/708cf160e0e0/Image%202019-05-31%20at%208.53.02%20PM.png)

Should I be able to see Avenir here?  I want it to be transparent to my user's that they're using a custom field.

Thanks!

**Comment by m10l** [comment]
@weotch Hi Robert! Thanks for taking the time to create an issue. We're currently doing the following in our [Optimizely UI extension](https://github.com/contentful/extensions/blob/optimizely/samples/optimizely/src/index.css), which should work if your extension is hosted on `app.contentful.com`.

```css
body {
  font-family: 'Avenir Next W01', -apple-system, BlinkMacSystemTypography, 'Segoe UI', Cantarell,
    Helvetica, Arial, sans-serif;
}

@font-face {
  font-family: 'Avenir Next W01';
  src: url('https://static.contentful.com/app/avenir-regular-normal-457e94a5b6.woff2')
    format('woff2');
  font-weight: 500;
  font-style: normal;
}

@font-face {
  font-family: 'Avenir Next W01';
  src: url('https://static.contentful.com/app/avenir-medium-normal-24932ad03d.woff2')
    format('woff2');
  font-weight: 600;
  font-style: normal;
}

@font-face {
  font-family: 'Avenir Next W01';
  src: url('https://static.contentful.com/app/avenir-demibold-normal-d42bfc911f.woff2')
    format('woff2');
  font-weight: 700;
  font-style: normal;
}
```

This should be treated as a temporary workaround however, as we're currently looking into a solution which has the potential to make the above redundant.
